### ISSUE TITLE
php missing some file

### ISSUE THREAD

**Issue by NoreiT** [ctubio/php-cgminer-monitor#1]
Hi,
I tried to use your monitor but have a problem, when used there is php error

Warning: require(vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/index.php on line 4

Fatal error: require(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/index.php on line 4

dont really see this file anywhere.

Can you please help?
Thanks

-noreit

**Comment by NoreiT** [comment]
Sorry, I had to do "php composer.phar install" than install is missing in your guide :)

**Comment by zurylostboys** [comment]
how to do that ?? im using xamp is that ok to use

**Comment by NoreiT** [comment]
How to do what?

**Comment by zurylostboys** [comment]
to run this think since i always get error  ...

**Comment by NoreiT** [comment]
Which error do you see? You definitely need to install composer.phar as otherwise you will see missing files error.

**Comment by ctubio** [comment]
ima leave this here https://getcomposer.org/doc/01-basic-usage.md#installing-dependencies
